### PR TITLE
Fix build issues

### PR DESCRIPTION
**Pull request by onevcat**
This PR:

1. Upgrade the min version from 19 to 21. So we can get rid of the multiple DEX issue completely. Since the LINE SDK native for Android will increase the min SDK version very soon, it does not make sense to continue support Android 4.4 for this repo now.
2. Removes `android.enableJetifier` and `android.enableR8` in demo gradle property file. They are not compatible in older Unity versions and the later ones. So I removed them. The users should be asked to keep their own template files and only adding the necessary ones to the gradle files and properties. I will later try to upgrade the documentation to make this clearer.
3. I have to add the `androidx.lifecycle:lifecycle-viewmodel-ktx` to the build.gradle, unless it complains about a duplicated class [as I commented](https://github.com/line/line-sdk-unity/pull/54#issuecomment-1647167715) in #54. I found this solution [from this link](https://stackoverflow.com/questions/69817925/problem-duplicate-class-androidx-lifecycle-viewmodel-found-in-modules), but not sure what is it. I need some help on this. @tsairene @plateaukao Any idea or comment? Is there a better way?

### CODE REVIEW

**Comment by tsairene** [comment]
actually, I added `androidx.lifecycle:lifecycle-viewmodel-ktx` in previous PR[#53](https://github.com/line/line-sdk-unity/pull/53) as well to be able to compile on 2022 but it doesn't work on my 2020. not sure why...

**Comment by onevcat** [comment]
> actually, I added androidx.lifecycle:lifecycle-viewmodel-ktx in previous PRhttps://github.com/line/line-sdk-unity/pull/53 as well to be able to compile on 2022 but it doesn't work on my 2020. not sure why...

Do you still remember what was the error?

I found it was quite hard and too tricky to continue the compile on 2020.3.0, since it was using a quite legacy Gradle. However, starting from 2020.3.15 Unity uses a newer version and things go better.

**Comment by tsairene** [comment]
I am trying to checkout this PR locally and install 2020.3.15 to build. Will get back to you later

**Comment by onevcat** [comment]
@tsairene Hi, is there any news from your last comment?

**Comment by tsairene** [comment]
@onevcat 
Finally, get it built successfully after some environment clean up (tried clear all cache, remove output folder, re-install unity and so on...) I think it's good to merge now :D

**Pull request merged**
