### PR TITLE
Drop CocoaPods and Carthage, use built-in xcframework

### PR DESCRIPTION
**Pull request by onevcat**
This PR contains these changes:

- Remove the related post-build script for adding LINE SDK Swift by CocoaPods or Carthage.
- Remove the settings of LINE SDK for switching between CocoaPods and Carthage.
- Add the prebuilt xcframework to the project.
- Add a new post-build script to add the xcframework to the exported Xcode project. (Unity now only supports adding `.framework` automatically so we have to add the `xcframework` ourselves).

I will also update the documentation to reflect this change too after it can be merged. The existing users have to remove the old package and re-import the new one to get rid of the outdated (removed) CocoaPods/Carthage scripts. But there is no API changes so I guess we can release it as a minor version, something like 1.2.0 for example.

### CODE REVIEW

**Comment by eJamesLin** [comment]
It's cool to adopt native xcframework 👍 👍 👍 

I'm not familiar with Unity, not sure if lots of .meta files are required to be in git.
Also the Localizable.strings might have unrelated strings.

**Comment by onevcat** [comment]
The meta files are automatically generated by Unity when importing any files into the project. In this PR, most are not used and tracking nothing, but in deed some of them are important, such as [this one](https://github.com/line/line-sdk-unity/pull/46/files#diff-e4133e084e415c8497bfa560ec36d380332c4fcb9e514dfca1ab2399333f4c51). It records the fact that we do not want Unity to merely copy the `framework` file to the Xcode project (the whole `xcframework` should be treated and used as one in whole). So we need to leave it at least.

For other not in use ones, since Unity will just also generate them when the user importing them, I guess it would be no harm to leave as they are now. In the [post build script](https://github.com/line/line-sdk-unity/pull/46/files#diff-9e467819768bf68d4a196bcc92a69ccb664eece54f2f3df9c5867bd1c08afa98R75-R77) we are making sure to remove the `meta` to prevent it from being copied to the final exported Xcode project, where they are not necessary at all.

**Review by eJamesLin — APPROVED** [review]
LGTM

**Comment by ynaoto** [comment]
When can I expect to have new release that includes this change?  This would be very useful for me to drive automated build.

**Comment by onevcat** [comment]
I wish I could prepare a release tag for it as soon as possible, but unfortunately I am already on vacation now and cannot reach my working computer. So I am afraid I have to do it after the new year. Does that sound fine to you?

**Comment by onevcat** [comment]
Before that, it is totally fine to use this branch to get these changes!

**Comment by ynaoto** [comment]
It would be great if I may have the new package in the early new year.  Enjoy your holodays!

**Comment by onevcat** [comment]
I will merge it for now and going to write a new installation guide for it. Once the documentation can be done, I will tag it and make a new release.

**Comment by onevcat** [comment]
The new version 1.2.0 was released with these changes. I am going to delete the `fix/ios-integration` branch for now and please switch to using the released version instead.

Thanks!

**Pull request merged**
