### PR TITLE
added LANG=en_US.UTF-8 and handle exit code

### PR DESCRIPTION
**Pull request by ynaoto**

### CODE REVIEW

**Comment by onevcat** [comment]
Hi,

Thanks for this. We have already noticed this requirement and I think this fix would work fine.

However, we are now working on a new method to integrate LINE SDK into an iOS project in a less invasive way. So once the CLA can be signed, we can merge it and rebase our changes. But I guess there is no time schedule to make a release with this change before the new way out.

**Comment by ynaoto** [comment]
Signed TLA

**Comment by onevcat** [comment]
Thank you for the feedback. But it seems that it is still pending. Sorry but can you please check the status to see if it is fine?

**Comment by onevcat** [comment]
Please allow me to close it since covered by #46

**Pull request closed without merging**
